# Generated by Django 5.2.3 on 2025-06-28 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.file')),
            ],
        ),
        migrations.CreateModel(
            name='FilePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveSmallIntegerField()),
                ('data', models.BinaryField()),
                ('checksum', models.CharField(max_length=64)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='storage.file')),
            ],
            options={
                'unique_together': {('file', 'part_number')},
            },
        ),
    ]
